# Generated by Django 3.0.4 on 2020-03-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeTracker', '0005_vacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='date',
            field=models.DateField(),
        ),
    ]
